spring.application.name=gestao-convenios-api

spring.datasource.url=jdbc:postgresql://postgres:5432/gestaoconvenios
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true

# api.security.token.secret=uEe#2-zLfa3jV->RHcZy9ggC.gY5F~B%y5#6*u5>kJ)^t7Cj+jC,m45oV9xq@:22MvV:}3
# api.security.token.expiration=7200000