CREATE TABLE empresa_conveniada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(250) NOT NULL,
    cnpj VARCHAR(50) NOT NULL UNIQUE,
    endereco VARCHAR(250) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    excluida BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
);

CREATE TABLE contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    cargo VARCHAR(50) NOT NULL,
    telefone VARCHAR(50) NOT NULL,
    empresa_conveniada_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,

    CONSTRAINT fk_contato_empresa FOREIGN KEY (empresa_conveniada_id) REFERENCES empresa_conveniada(id)
);

